### PR TITLE
Add the option to expose Cover as a Window Accessory

### PR DESCRIPTION
**Pull request by joaodforce**
This PR aims to resolve my issue https://github.com/itavero/homebridge-z2m/issues/484

It adds the option to convert a cover accessory into a window one.

I based myself off the existing [switch converter](https://github.com/itavero/homebridge-z2m/blob/master/src/converters/switch.ts)

### CODE REVIEW

**Comment by itavero** [comment]
Haven't reviewed the code yet, but it seems that the tests, change log and docs have not been updated.

**Comment by joaodforce** [comment]
> Haven't reviewed the code yet, but it seems that the tests, change log and docs have not been updated.

Sorry about that, I updated the docs and the change log.

I also made a test case for it as well, but you'll have to excuse me if I did something wrong, I'm not very experience with test cases yet.

I copied one of the window test cases, modified it so it would set the type to window based on how its done in the `switch.spec.ts` file, and then modified the tests to test for `Window` instead of `WindowCovering`

Then all the tests passed, then I commented the config line to test if it would fail, and it did as expected.

Please tell me if something else needs to be changed.

**Comment by itavero** [comment]
Seems to look okay so far, but I only had a quick glance. Hopefully I have some time soon to do an in depth review before merging it. Thanks for your work so far!

**Comment by itavero** [comment]
Unfortunately I've not been able to find time yet to review this (it's also quite hot these last few weeks in the Netherlands, so not the best weather to be in my home office or have a hot laptop near me 😅).
Just wanted to let you know that I haven't forgotten about your PR.

**Comment by joaodforce** [comment]
> Unfortunately I've not been able to find time yet to review this (it's also quite hot these last few weeks in the Netherlands, so not the best weather to be in my home office or have a hot laptop near me 😅).
> Just wanted to let you know that I haven't forgotten about your PR.

No problem! Take your time.

**Review by itavero — CHANGES_REQUESTED** [review]
Added a few remarks.

I haven't been able to test this myself yet, but have you also verified that the Window service gets cleaned up correctly when the configuration is changed back to Window Covering (and vice versa)?

**Pull request closed without merging**
